apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    {{- include "tagsphere.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.backend.secrets.JWT_SECRET | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.backend.secrets.ENCRYPTION_KEY | b64enc | quote }}
  OTP_API_KEY: {{ .Values.backend.secrets.OTP_API_KEY | b64enc | quote }}
