apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    {{- include "tagsphere.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.backend.secrets.JWT_SECRET | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.backend.secrets.ENCRYPTION_KEY | b64enc | quote }}
  {{- if eq .Values.backend.env.ENABLE_FIREBASE "true" }}
  FIREBASE_PROJECT_ID: {{ .Values.backend.secrets.FIREBASE_PROJECT_ID | b64enc | quote }}
  FIREBASE_CLIENT_EMAIL: {{ .Values.backend.secrets.FIREBASE_CLIENT_EMAIL | b64enc | quote }}
  FIREBASE_PRIVATE_KEY: {{ .Values.backend.secrets.FIREBASE_PRIVATE_KEY | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.backend.env.ENABLE_RAZORPAY "true" }}
  RAZORPAY_KEY_ID: {{ .Values.backend.secrets.RAZORPAY_KEY_ID | b64enc | quote }}
  RAZORPAY_KEY_SECRET: {{ .Values.backend.secrets.RAZORPAY_KEY_SECRET | b64enc | quote }}
  {{- end }}
