apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
  labels:
    app: mongodb
    {{- include "tagsphere.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: mongodb
