{{- if .Values.mongodb.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: mongodb
    {{- include "tagsphere.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.mongodb.auth.rootUsername | b64enc | quote }}
  password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
{{- end }}
