apiVersion: v1
kind: ServiceAccount
metadata:
  name: tagsphere-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    {{- include "tagsphere.labels" . | nindent 4 }}
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tagsphere-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    {{- include "tagsphere.labels" . | nindent 4 }}
automountServiceAccountToken: false
